---
- hosts: webservers

  tasks:

  - name: add server block
    template:
      src: templates/server-block.conf
      dest: /etc/nginx/conf.d/{{ domain }}.conf

  - name: reload nginx
    service:
      name: nginx
      state: reloaded
