---
- hosts: webservers

  tasks:

  - name: add server block
    template: src=templates/server-block.conf dest=/etc/nginx/sites-available/{{ domain }}.conf

  - name: enable server block
    file: src=/etc/nginx/sites-available/{{ domain }}.conf dest=/etc/nginx/sites-enabled/{{ domain }}.conf state=link

  - name: reload nginx
    service: name=nginx state=reloaded